#! /bin/bash -x

set -e

git submodule update --init

cd upstream

git fetch

git branch -D auto-generator
git branch --force auto-generator "${1-origin/master}"

git submodule update --init

git checkout auto-generator
git reset --hard auto-generator


VERSIONS=$(sed -n 's/^VERSIONS[[:space:]]*=//p' Makefile)
git clean -d -f
make generate-all

tag=$(git rev-parse HEAD)

cd ..

git clean -d -f

for version in $VERSIONS; do
    case $version in
        */*|*..*)
            false "bad version"
            ;;
    esac

    rm  -rf "$version"
    git rm -r "$version"

    no_symlink=$(readlink -f "upstream/$version")
    cp -r "$no_symlink" "$version"
    git add -f "$version"
done

if ! git diff --cached --exit-code --quiet ; then
    git commit -m "auto-sync: upstream commit $tag"
    git tag "upstream-$tag"
else
    echo "nothing changed"
fi
